FROM node:18

# dossier de travail dans le conteneur
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . . 

# Installer net-tools pour utiliser netstat
#RUN apt-get update && apt-get install -y net-tools

# Build application
RUN npm run build

CMD ["npm", "run", "start"]

EXPOSE 4000
